### PR TITLE
feat(revalidate): implements revalidate for post related terms

### LINKED ISSUE #295: On-Demand Revalidation for archive pages
We should also revalidate archive pages (category, tags, etc) that belongs to a post being updated. We should limit to revalidating only the first two pages but offer a filter to allow revalidating more pages.

### PR DESCRIPTION
**Pull request by orballo**
### Description of the Change

Closes #295 

Child PR: #535 

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @orballo 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly. (Will do in another PR, after `post_type` archives revalidation is implemented)
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### TODO:
- [ ] Modify projects to add `getStaticPaths` to the archives paths. (Will do this in another PR)
- [ ] Add tests for the PHP part. (Will do this in another PR)
- [x] Verify that the terms revalidation is working.
- [x] Add support for `post_type` archives. (https://github.com/10up/headstartwp/pull/535)

### CODE REVIEW

**Comment by orballo** [comment]
#### TODO:
- [ ] Modify projects to add `getStaticPaths` to the archives paths.
- [ ] Verify that the terms revalidation is working.
- [ ] Add support for `post_type` archives.
- [ ] Add tests.

**Comment by orballo** [comment]
@nicholasio This PR is getting too big. Could you please review it?

I still need to add the revalidate for the `post_type` archives, modify the existing projects to use this functionality, and update the docs. But I want to do this in three different PRs.

**Comment by nicholasio** [comment]
I did some testing and couldn't get term archives to be revalidated. Next.js is returning missing params.

**Comment by orballo** [comment]
@nicholasio I didn't forget about this. I'll work on it as soon as I find some time.

**Pull request closed without merging**
