### PR TITLE
WP Plugin - Rector - automatic and manual fixes

### PR DESCRIPTION
**Pull request by claytoncollie**
### Description of the Change
This PR adds Rector to the wp plugin and a GitHub action to enforce the coding standards in the future.

Requires #696 

Part 4 for addressing #625 

### Credits
Props @claytoncollie

### CODE REVIEW

**Review by nicholasio — APPROVED** [review]

**Review by nicholasio — APPROVED** [review]

**Comment by nicholasio** [comment]
Even though this is passing tests something in the  changes here broke at least preview. So we can't merge this right now. Need to look further into it

**Comment by claytoncollie** [comment]
@nicholasio Thanks for merging the other PRs. I will look at this PR next week and also start one for PHPStan. Rector can be heavy-handed so it might take a little bit to dial it in.

**Comment by claytoncollie** [comment]
@nicholasio I merged `develop` into this branch and re-ran the linting and refactor scripts. The phpunit tests are still failing for some reason but this might be good to recheck the Preview functionality when you get a chance.

**Comment by nicholasio** [comment]
This is causing multiple errors. Rector is definately making breaking changes. I appreciate all the work here but I believe this is too risky to merge at this point. It would require a full QA round to ensure everything is working as expected as our php tests do not cover everything.

I'm going to close this for now, perhaps we can revisit it once we have better tests coverage for the plugin and the e2e tests set up.

**Pull request closed without merging**
